Fix build on FreeBSD/powerpc*.
lr collides with lr from machine/frame.h header (link register):
In file included from /wrkdirs/usr/ports/science/hypre/work/hypre-2.23.0/src/distributed_ls/pilut/parilut.c:53:
In file included from /wrkdirs/usr/ports/science/hypre/work/hypre-2.23.0/src/distributed_ls/pilut/ilu.h:29:
In file included from /usr/include/signal.h:40:
In file included from /usr/include/sys/signal.h:48:
In file included from /usr/include/machine/signal.h:45:
/usr/include/machine/frame.h:54:13: error: expected ')'
        register_t lr;